import { createClient } from '@/lib/supabase/server'
import { getDictionary } from '@/lib/dictionaries'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Wallet, Download } from 'lucide-react'

export default async function StudentFeesPage({ params }: { params: Promise<{ lang: string }> }) {
  const { lang } = await params
  const dict = await getDictionary(lang)
  const supabase = await createClient()

  const { data: { user } } = await supabase.auth.getUser()

  const { data: student } = await (supabase
    .from('students')
    .select('id')
    .eq('profile_id', user?.id ?? '')
    .maybeSingle()) as any

  const { data: vouchers } = await (supabase
    .from('fee_vouchers')
    .select('*')
    .eq('student_id', student?.id ?? '')
    .order('due_date', { ascending: false })) as any

  const statusColor: Record<string, string> = {
    paid: 'bg-green-500',
    unpaid: 'bg-amber-500',
    overdue: 'bg-red-500',
    waived: 'bg-blue-500',
  }

  const totalDue = (vouchers as any[] ?? [])
    .filter((v) => v.status === 'unpaid' || v.status === 'overdue')
    .reduce((sum: number, v: any) => sum + Number(v.amount), 0)

  return (
    <div className="space-y-6">
      <h2 className="text-2xl font-bold tracking-tight">{dict.nav.fees}</h2>

      {/* Summary */}
      {totalDue > 0 && (
        <Card className="border-amber-200 bg-amber-50 dark:bg-amber-950 dark:border-amber-800">
          <CardContent className="pt-5 flex items-center justify-between gap-4 flex-wrap">
            <div>
              <p className="text-sm font-medium text-amber-700 dark:text-amber-300">Outstanding Balance</p>
              <p className="text-3xl font-bold text-amber-800 dark:text-amber-200">PKR {totalDue.toLocaleString()}</p>
            </div>
            <Button className="bg-primary text-white">Pay Now via JazzCash</Button>
          </CardContent>
        </Card>
      )}

      {/* Vouchers */}
      <Card className="border-primary/10 shadow-sm">
        <CardHeader>
          <div className="flex items-center gap-2">
            <Wallet className="w-4 h-4 text-primary" />
            <CardTitle className="text-base">Fee Vouchers</CardTitle>
          </div>
        </CardHeader>
        <CardContent>
          {vouchers?.length ? (
            <div className="space-y-3">
              {(vouchers as any[]).map((v) => (
                <div key={v.id} className="flex items-center justify-between p-4 rounded-lg border border-border">
                  <div>
                    <p className="font-medium text-sm">Voucher #{v.voucher_number}</p>
                    <p className="text-xs text-muted-foreground mt-0.5">
                      Due: {new Date(v.due_date).toLocaleDateString()} • {v.month_year}
                    </p>
                    {v.paid_at && (
                      <p className="text-xs text-green-600 mt-0.5">
                        Paid on {new Date(v.paid_at).toLocaleDateString()}
                      </p>
                    )}
                  </div>
                  <div className="flex items-center gap-3">
                    <div className="text-right">
                      <p className="font-bold">PKR {Number(v.amount).toLocaleString()}</p>
                      <Badge className={`${statusColor[v.status] ?? 'bg-gray-400'} text-white text-xs mt-1 capitalize`}>
                        {v.status}
                      </Badge>
                    </div>
                    <Button variant="ghost" size="icon" title="Download Voucher">
                      <Download className="w-4 h-4" />
                    </Button>
                  </div>
                </div>
              ))}
            </div>
          ) : (
            <div className="text-center py-12 text-muted-foreground">
              <Wallet className="w-10 h-10 mx-auto mb-3 opacity-20" />
              <p className="text-sm font-medium">No vouchers yet</p>
              <p className="text-xs mt-1">Fee vouchers will appear here once generated by the admin.</p>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  )
}
