/**
 * Professional PDF Generation Service
 * Generates branded PDFs for various documents
 */

import jsPDF from 'jspdf'
import 'jspdf-autotable'

type Institution = {
  name: string
  urdu_name?: string
  logo_url?: string
  address?: string
  phone?: string
  email?: string
}

export class PDFGenerator {
  private doc: jsPDF
  private institution: Institution
  private currentY: number = 20

  constructor(institution: Institution) {
    this.doc = new jsPDF()
    this.institution = institution
  }

  private addHeader() {
    const pageWidth = this.doc.internal.pageSize.width

    // Add logo if available
    if (this.institution.logo_url) {
      // TODO: Load and add logo image
    }

    // Institution name (centered)
    this.doc.setFontSize(20)
    this.doc.setFont('helvetica', 'bold')
    this.doc.text(this.institution.name, pageWidth / 2, 20, { align: 'center' })

    if (this.institution.urdu_name) {
      this.doc.setFontSize(16)
      this.doc.text(this.institution.urdu_name, pageWidth / 2, 28, { align: 'center' })
    }

    // Institution details
    this.doc.setFontSize(9)
    this.doc.setFont('helvetica', 'normal')
    let detailsY = this.institution.urdu_name ? 35 : 28

    if (this.institution.address) {
      this.doc.text(this.institution.address, pageWidth / 2, detailsY, { align: 'center' })
      detailsY += 5
    }

    if (this.institution.phone || this.institution.email) {
      const contact = [this.institution.phone, this.institution.email].filter(Boolean).join(' | ')
      this.doc.text(contact, pageWidth / 2, detailsY, { align: 'center' })
      detailsY += 5
    }

    // Separator line
    this.doc.setLineWidth(0.5)
    this.doc.line(15, detailsY + 2, pageWidth - 15, detailsY + 2)

    this.currentY = detailsY + 10
  }

  private addFooter() {
    const pageHeight = this.doc.internal.pageSize.height
    const pageWidth = this.doc.internal.pageSize.width

    this.doc.setFontSize(8)
    this.doc.setFont('helvetica', 'italic')
    this.doc.text('Generated by Jamia Management System', pageWidth / 2, pageHeight - 10, { align: 'center' })
    this.doc.text(`Date: ${new Date().toLocaleDateString()}`, pageWidth / 2, pageHeight - 6, { align: 'center' })
  }

  // Fee Voucher Generation
  generateFeeVoucher(voucher: any, student: any, feeBreakdown: any) {
    this.addHeader()

    const pageWidth = this.doc.internal.pageSize.width

    // Document title
    this.doc.setFontSize(16)
    this.doc.setFont('helvetica', 'bold')
    this.doc.text('FEE VOUCHER', pageWidth / 2, this.currentY, { align: 'center' })
    this.currentY += 10

    // Voucher details box
    this.doc.setFontSize(10)
    this.doc.setFont('helvetica', 'normal')

    const leftCol = 20
    const rightCol = pageWidth / 2 + 10

    // Student information
    this.doc.setFont('helvetica', 'bold')
    this.doc.text('Student Information:', leftCol, this.currentY)
    this.currentY += 7

    this.doc.setFont('helvetica', 'normal')
    this.doc.text(`Name: ${student.name_en}`, leftCol, this.currentY)
    this.currentY += 6

    if (student.name_ur) {
      this.doc.text(`نام: ${student.name_ur}`, leftCol, this.currentY)
      this.currentY += 6
    }

    this.doc.text(`Admission #: ${student.admission_number}`, leftCol, this.currentY)
    this.currentY += 6

    if (student.father_name_en) {
      this.doc.text(`Father: ${student.father_name_en}`, leftCol, this.currentY)
      this.currentY += 6
    }

    this.currentY += 5

    // Voucher information
    this.doc.setFont('helvetica', 'bold')
    this.doc.text('Voucher Information:', leftCol, this.currentY)
    this.currentY += 7

    this.doc.setFont('helvetica', 'normal')
    this.doc.text(`Voucher #: ${voucher.voucher_number}`, leftCol, this.currentY)
    this.currentY += 6

    this.doc.text(`Month: ${voucher.month_year}`, leftCol, this.currentY)
    this.currentY += 6

    this.doc.text(`Due Date: ${new Date(voucher.due_date).toLocaleDateString()}`, leftCol, this.currentY)
    this.currentY += 6

    const statusColor = voucher.status === 'paid' ? 'green' : voucher.status === 'unpaid' ? 'red' : 'orange'
    this.doc.setTextColor(statusColor === 'green' ? 0 : statusColor === 'red' ? 255 : 255, statusColor === 'green' ? 128 : 165, 0)
    this.doc.text(`Status: ${voucher.status.toUpperCase()}`, leftCol, this.currentY)
    this.doc.setTextColor(0, 0, 0)
    this.currentY += 10

    // Fee breakdown table
    this.doc.setFont('helvetica', 'bold')
    this.doc.text('Fee Breakdown:', leftCol, this.currentY)
    this.currentY += 7

    const tableData = []

    if (feeBreakdown.monthly_tuition > 0) {
      tableData.push(['Monthly Tuition', `PKR ${feeBreakdown.monthly_tuition.toLocaleString()}`])
    }
    if (feeBreakdown.hostel_fee > 0) {
      tableData.push(['Hostel Fee', `PKR ${feeBreakdown.hostel_fee.toLocaleString()}`])
    }
    if (feeBreakdown.mess_fee > 0) {
      tableData.push(['Mess Fee', `PKR ${feeBreakdown.mess_fee.toLocaleString()}`])
    }
    if (feeBreakdown.transport_fee > 0) {
      tableData.push(['Transport Fee', `PKR ${feeBreakdown.transport_fee.toLocaleString()}`])
    }
    if (feeBreakdown.exam_fee > 0) {
      tableData.push(['Examination Fee', `PKR ${feeBreakdown.exam_fee.toLocaleString()}`])
    }
    if (feeBreakdown.library_fee > 0) {
      tableData.push(['Library Fee', `PKR ${feeBreakdown.library_fee.toLocaleString()}`])
    }
    if (voucher.previous_balance > 0) {
      tableData.push(['Previous Balance', `PKR ${voucher.previous_balance.toLocaleString()}`])
    }
    if (voucher.discount_amount > 0) {
      tableData.push(['Discount', `- PKR ${voucher.discount_amount.toLocaleString()}`])
    }
    if (voucher.late_fee > 0) {
      tableData.push(['Late Fee', `PKR ${voucher.late_fee.toLocaleString()}`])
    }

    ;(this.doc as any).autoTable({
      startY: this.currentY,
      head: [['Description', 'Amount']],
      body: tableData,
      theme: 'striped',
      headStyles: { fillColor: [30, 58, 138], textColor: 255, fontStyle: 'bold' },
      styles: { fontSize: 10 },
      columnStyles: {
        0: { cellWidth: 120 },
        1: { cellWidth: 60, halign: 'right' },
      },
    })

    this.currentY = (this.doc as any).lastAutoTable.finalY + 10

    // Total amount box
    this.doc.setFillColor(30, 58, 138)
    this.doc.rect(leftCol, this.currentY, pageWidth - 40, 12, 'F')

    this.doc.setTextColor(255, 255, 255)
    this.doc.setFont('helvetica', 'bold')
    this.doc.setFontSize(12)
    this.doc.text('TOTAL AMOUNT:', leftCol + 5, this.currentY + 8)
    this.doc.text(`PKR ${voucher.total_amount.toLocaleString()}`, pageWidth - 25, this.currentY + 8, { align: 'right' })
    this.doc.setTextColor(0, 0, 0)

    this.currentY += 20

    // Payment instructions
    this.doc.setFontSize(9)
    this.doc.setFont('helvetica', 'italic')
    this.doc.text('Payment Instructions:', leftCol, this.currentY)
    this.currentY += 5
    this.doc.setFont('helvetica', 'normal')
    this.doc.text('• Please pay before the due date to avoid late fees', leftCol + 5, this.currentY)
    this.currentY += 5
    this.doc.text('• Keep this voucher for your records', leftCol + 5, this.currentY)
    this.currentY += 5
    this.doc.text('• Contact the accounts office for any queries', leftCol + 5, this.currentY)

    this.addFooter()

    return this.doc
  }

  // Result Card Generation
  generateResultCard(result: any, student: any, exam: any, marks: any[]) {
    this.addHeader()

    const pageWidth = this.doc.internal.pageSize.width

    // Document title
    this.doc.setFontSize(16)
    this.doc.setFont('helvetica', 'bold')
    this.doc.text('RESULT CARD', pageWidth / 2, this.currentY, { align: 'center' })
    this.currentY += 10

    // Student and exam info
    this.doc.setFontSize(10)
    const leftCol = 20
    const rightCol = pageWidth / 2 + 10

    this.doc.setFont('helvetica', 'bold')
    this.doc.text('Student:', leftCol, this.currentY)
    this.doc.text('Exam:', rightCol, this.currentY)
    this.currentY += 6

    this.doc.setFont('helvetica', 'normal')
    this.doc.text(student.name_en, leftCol, this.currentY)
    this.doc.text(exam.name_en, rightCol, this.currentY)
    this.currentY += 6

    if (student.name_ur) {
      this.doc.text(student.name_ur, leftCol, this.currentY)
      if (exam.name_ur) {
        this.doc.text(exam.name_ur, rightCol, this.currentY)
      }
      this.currentY += 6
    }

    this.doc.text(`Admission #: ${student.admission_number}`, leftCol, this.currentY)
    this.doc.text(`Type: ${exam.exam_type}`, rightCol, this.currentY)
    this.currentY += 6

    if (student.father_name_en) {
      this.doc.text(`Father: ${student.father_name_en}`, leftCol, this.currentY)
    }
    this.doc.text(`Date: ${new Date(exam.start_date).toLocaleDateString()}`, rightCol, this.currentY)
    this.currentY += 10

    // Marks table
    const tableData = marks.map((m: any) => [
      m.subject.name_en,
      m.exam_subject.total_marks,
      m.exam_subject.passing_marks,
      m.is_absent ? 'Absent' : m.total_obtained,
      m.is_absent ? '-' : ((m.total_obtained / m.exam_subject.total_marks) * 100).toFixed(1) + '%',
      m.is_absent ? 'Absent' : m.total_obtained >= m.exam_subject.passing_marks ? 'Pass' : 'Fail',
    ])

    ;(this.doc as any).autoTable({
      startY: this.currentY,
      head: [['Subject', 'Total', 'Passing', 'Obtained', 'Percentage', 'Result']],
      body: tableData,
      theme: 'grid',
      headStyles: { fillColor: [30, 58, 138], textColor: 255, fontStyle: 'bold' },
      styles: { fontSize: 9 },
      columnStyles: {
        1: { halign: 'center' },
        2: { halign: 'center' },
        3: { halign: 'center' },
        4: { halign: 'center' },
        5: { halign: 'center' },
      },
    })

    this.currentY = (this.doc as any).lastAutoTable.finalY + 10

    // Overall result box
    this.doc.setFillColor(result.is_pass ? 34 : 220, result.is_pass ? 197 : 38, result.is_pass ? 94 : 38)
    this.doc.rect(leftCol, this.currentY, pageWidth - 40, 25, 'F')

    this.doc.setTextColor(255, 255, 255)
    this.doc.setFont('helvetica', 'bold')
    this.doc.setFontSize(14)
    this.doc.text('OVERALL RESULT', pageWidth / 2, this.currentY + 8, { align: 'center' })

    this.doc.setFontSize(11)
    this.doc.text(`Marks: ${result.total_marks_obtained}/${result.total_marks_max}`, leftCol + 10, this.currentY + 18)
    this.doc.text(`Percentage: ${Number(result.percentage).toFixed(2)}%`, pageWidth / 2, this.currentY + 18, { align: 'center' })
    this.doc.text(`Grade: ${result.grade}`, pageWidth - 50, this.currentY + 18)

    this.doc.setTextColor(0, 0, 0)
    this.currentY += 30

    // Position and remarks
    this.doc.setFontSize(10)
    this.doc.setFont('helvetica', 'bold')
    this.doc.text(`Position: ${result.position}`, leftCol, this.currentY)
    this.doc.text(`Status: ${result.is_pass ? 'PASSED' : 'FAILED'}`, rightCol, this.currentY)
    this.currentY += 10

    if (result.remarks) {
      this.doc.setFont('helvetica', 'italic')
      this.doc.text(`Remarks: ${result.remarks}`, leftCol, this.currentY)
    }

    this.addFooter()

    return this.doc
  }

  // Generic method to save or return blob
  save(filename: string) {
    this.doc.save(filename)
  }

  output(type: 'blob' | 'bloburl' | 'datauristring' | 'datauri' = 'blob') {
    return this.doc.output(type)
  }
}

// Helper function to generate fee voucher
export async function generateFeeVoucherPDF(
  institution: Institution,
  voucher: any,
  student: any,
  feeBreakdown: any
) {
  const generator = new PDFGenerator(institution)
  const doc = generator.generateFeeVoucher(voucher, student, feeBreakdown)
  return doc.output('blob')
}

// Helper function to generate result card
export async function generateResultCardPDF(
  institution: Institution,
  result: any,
  student: any,
  exam: any,
  marks: any[]
) {
  const generator = new PDFGenerator(institution)
  const doc = generator.generateResultCard(result, student, exam, marks)
  return doc.output('blob')
}
